#!/usr/bin/env bash
python3 -c "import socket; s=socket.socket(); s.bind(('127.0.0.1',98)); s.listen(1); c,a=s.accept(); 
while True:
 data=c.recv(1024)
 if not data: break
 print(data.decode(), end='')"
